/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardMembroRouteImport } from './routes/dashboard/membro'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardMembroIndexRouteImport } from './routes/dashboard/membro/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardMembroRelatoriosRouteImport } from './routes/dashboard/membro/relatorios'
import { Route as DashboardMembroRankingRouteImport } from './routes/dashboard/membro/ranking'
import { Route as DashboardMembroPosicionamentoRouteImport } from './routes/dashboard/membro/posicionamento'
import { Route as DashboardMembroPilaresRouteImport } from './routes/dashboard/membro/pilares'
import { Route as DashboardMembroOkrRouteImport } from './routes/dashboard/membro/okr'
import { Route as DashboardMembroMarketingRouteImport } from './routes/dashboard/membro/marketing'
import { Route as DashboardMembroKpisRouteImport } from './routes/dashboard/membro/kpis'
import { Route as DashboardMembroAgendaRouteImport } from './routes/dashboard/membro/agenda'
import { Route as DashboardAdminRelatoriosRouteImport } from './routes/dashboard/admin/relatorios'
import { Route as DashboardAdminMembrosRouteImport } from './routes/dashboard/admin/membros'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMembroRoute = DashboardMembroRouteImport.update({
  id: '/dashboard/membro',
  path: '/dashboard/membro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMembroIndexRoute = DashboardMembroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardMembroRelatoriosRoute =
  DashboardMembroRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => DashboardMembroRoute,
  } as any)
const DashboardMembroRankingRoute = DashboardMembroRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardMembroPosicionamentoRoute =
  DashboardMembroPosicionamentoRouteImport.update({
    id: '/posicionamento',
    path: '/posicionamento',
    getParentRoute: () => DashboardMembroRoute,
  } as any)
const DashboardMembroPilaresRoute = DashboardMembroPilaresRouteImport.update({
  id: '/pilares',
  path: '/pilares',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardMembroOkrRoute = DashboardMembroOkrRouteImport.update({
  id: '/okr',
  path: '/okr',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardMembroMarketingRoute =
  DashboardMembroMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => DashboardMembroRoute,
  } as any)
const DashboardMembroKpisRoute = DashboardMembroKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardMembroAgendaRoute = DashboardMembroAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardAdminRelatoriosRoute =
  DashboardAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminMembrosRoute = DashboardAdminMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/membro': typeof DashboardMembroRouteWithChildren
  '/dashboard/admin/membros': typeof DashboardAdminMembrosRoute
  '/dashboard/admin/relatorios': typeof DashboardAdminRelatoriosRoute
  '/dashboard/membro/agenda': typeof DashboardMembroAgendaRoute
  '/dashboard/membro/kpis': typeof DashboardMembroKpisRoute
  '/dashboard/membro/marketing': typeof DashboardMembroMarketingRoute
  '/dashboard/membro/okr': typeof DashboardMembroOkrRoute
  '/dashboard/membro/pilares': typeof DashboardMembroPilaresRoute
  '/dashboard/membro/posicionamento': typeof DashboardMembroPosicionamentoRoute
  '/dashboard/membro/ranking': typeof DashboardMembroRankingRoute
  '/dashboard/membro/relatorios': typeof DashboardMembroRelatoriosRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/membro/': typeof DashboardMembroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin/membros': typeof DashboardAdminMembrosRoute
  '/dashboard/admin/relatorios': typeof DashboardAdminRelatoriosRoute
  '/dashboard/membro/agenda': typeof DashboardMembroAgendaRoute
  '/dashboard/membro/kpis': typeof DashboardMembroKpisRoute
  '/dashboard/membro/marketing': typeof DashboardMembroMarketingRoute
  '/dashboard/membro/okr': typeof DashboardMembroOkrRoute
  '/dashboard/membro/pilares': typeof DashboardMembroPilaresRoute
  '/dashboard/membro/posicionamento': typeof DashboardMembroPosicionamentoRoute
  '/dashboard/membro/ranking': typeof DashboardMembroRankingRoute
  '/dashboard/membro/relatorios': typeof DashboardMembroRelatoriosRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/membro': typeof DashboardMembroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/membro': typeof DashboardMembroRouteWithChildren
  '/dashboard/admin/membros': typeof DashboardAdminMembrosRoute
  '/dashboard/admin/relatorios': typeof DashboardAdminRelatoriosRoute
  '/dashboard/membro/agenda': typeof DashboardMembroAgendaRoute
  '/dashboard/membro/kpis': typeof DashboardMembroKpisRoute
  '/dashboard/membro/marketing': typeof DashboardMembroMarketingRoute
  '/dashboard/membro/okr': typeof DashboardMembroOkrRoute
  '/dashboard/membro/pilares': typeof DashboardMembroPilaresRoute
  '/dashboard/membro/posicionamento': typeof DashboardMembroPosicionamentoRoute
  '/dashboard/membro/ranking': typeof DashboardMembroRankingRoute
  '/dashboard/membro/relatorios': typeof DashboardMembroRelatoriosRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/membro/': typeof DashboardMembroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard/admin'
    | '/dashboard/membro'
    | '/dashboard/admin/membros'
    | '/dashboard/admin/relatorios'
    | '/dashboard/membro/agenda'
    | '/dashboard/membro/kpis'
    | '/dashboard/membro/marketing'
    | '/dashboard/membro/okr'
    | '/dashboard/membro/pilares'
    | '/dashboard/membro/posicionamento'
    | '/dashboard/membro/ranking'
    | '/dashboard/membro/relatorios'
    | '/dashboard/admin/'
    | '/dashboard/membro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/admin/membros'
    | '/dashboard/admin/relatorios'
    | '/dashboard/membro/agenda'
    | '/dashboard/membro/kpis'
    | '/dashboard/membro/marketing'
    | '/dashboard/membro/okr'
    | '/dashboard/membro/pilares'
    | '/dashboard/membro/posicionamento'
    | '/dashboard/membro/ranking'
    | '/dashboard/membro/relatorios'
    | '/dashboard/admin'
    | '/dashboard/membro'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard/admin'
    | '/dashboard/membro'
    | '/dashboard/admin/membros'
    | '/dashboard/admin/relatorios'
    | '/dashboard/membro/agenda'
    | '/dashboard/membro/kpis'
    | '/dashboard/membro/marketing'
    | '/dashboard/membro/okr'
    | '/dashboard/membro/pilares'
    | '/dashboard/membro/posicionamento'
    | '/dashboard/membro/ranking'
    | '/dashboard/membro/relatorios'
    | '/dashboard/admin/'
    | '/dashboard/membro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardMembroRoute: typeof DashboardMembroRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/membro': {
      id: '/dashboard/membro'
      path: '/dashboard/membro'
      fullPath: '/dashboard/membro'
      preLoaderRoute: typeof DashboardMembroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/membro/': {
      id: '/dashboard/membro/'
      path: '/'
      fullPath: '/dashboard/membro/'
      preLoaderRoute: typeof DashboardMembroIndexRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/membro/relatorios': {
      id: '/dashboard/membro/relatorios'
      path: '/relatorios'
      fullPath: '/dashboard/membro/relatorios'
      preLoaderRoute: typeof DashboardMembroRelatoriosRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/ranking': {
      id: '/dashboard/membro/ranking'
      path: '/ranking'
      fullPath: '/dashboard/membro/ranking'
      preLoaderRoute: typeof DashboardMembroRankingRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/posicionamento': {
      id: '/dashboard/membro/posicionamento'
      path: '/posicionamento'
      fullPath: '/dashboard/membro/posicionamento'
      preLoaderRoute: typeof DashboardMembroPosicionamentoRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/pilares': {
      id: '/dashboard/membro/pilares'
      path: '/pilares'
      fullPath: '/dashboard/membro/pilares'
      preLoaderRoute: typeof DashboardMembroPilaresRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/okr': {
      id: '/dashboard/membro/okr'
      path: '/okr'
      fullPath: '/dashboard/membro/okr'
      preLoaderRoute: typeof DashboardMembroOkrRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/marketing': {
      id: '/dashboard/membro/marketing'
      path: '/marketing'
      fullPath: '/dashboard/membro/marketing'
      preLoaderRoute: typeof DashboardMembroMarketingRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/kpis': {
      id: '/dashboard/membro/kpis'
      path: '/kpis'
      fullPath: '/dashboard/membro/kpis'
      preLoaderRoute: typeof DashboardMembroKpisRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/agenda': {
      id: '/dashboard/membro/agenda'
      path: '/agenda'
      fullPath: '/dashboard/membro/agenda'
      preLoaderRoute: typeof DashboardMembroAgendaRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/admin/relatorios': {
      id: '/dashboard/admin/relatorios'
      path: '/relatorios'
      fullPath: '/dashboard/admin/relatorios'
      preLoaderRoute: typeof DashboardAdminRelatoriosRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/membros': {
      id: '/dashboard/admin/membros'
      path: '/membros'
      fullPath: '/dashboard/admin/membros'
      preLoaderRoute: typeof DashboardAdminMembrosRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminMembrosRoute: typeof DashboardAdminMembrosRoute
  DashboardAdminRelatoriosRoute: typeof DashboardAdminRelatoriosRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminMembrosRoute: DashboardAdminMembrosRoute,
  DashboardAdminRelatoriosRoute: DashboardAdminRelatoriosRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardMembroRouteChildren {
  DashboardMembroAgendaRoute: typeof DashboardMembroAgendaRoute
  DashboardMembroKpisRoute: typeof DashboardMembroKpisRoute
  DashboardMembroMarketingRoute: typeof DashboardMembroMarketingRoute
  DashboardMembroOkrRoute: typeof DashboardMembroOkrRoute
  DashboardMembroPilaresRoute: typeof DashboardMembroPilaresRoute
  DashboardMembroPosicionamentoRoute: typeof DashboardMembroPosicionamentoRoute
  DashboardMembroRankingRoute: typeof DashboardMembroRankingRoute
  DashboardMembroRelatoriosRoute: typeof DashboardMembroRelatoriosRoute
  DashboardMembroIndexRoute: typeof DashboardMembroIndexRoute
}

const DashboardMembroRouteChildren: DashboardMembroRouteChildren = {
  DashboardMembroAgendaRoute: DashboardMembroAgendaRoute,
  DashboardMembroKpisRoute: DashboardMembroKpisRoute,
  DashboardMembroMarketingRoute: DashboardMembroMarketingRoute,
  DashboardMembroOkrRoute: DashboardMembroOkrRoute,
  DashboardMembroPilaresRoute: DashboardMembroPilaresRoute,
  DashboardMembroPosicionamentoRoute: DashboardMembroPosicionamentoRoute,
  DashboardMembroRankingRoute: DashboardMembroRankingRoute,
  DashboardMembroRelatoriosRoute: DashboardMembroRelatoriosRoute,
  DashboardMembroIndexRoute: DashboardMembroIndexRoute,
}

const DashboardMembroRouteWithChildren = DashboardMembroRoute._addFileChildren(
  DashboardMembroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardMembroRoute: DashboardMembroRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
