services:
  - type: web
    name: arquitetura-relevancia-hub
    env: static
    rootDir: arquitetura-hub
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
