/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardMembroRouteImport } from './routes/dashboard/membro'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardMembroIndexRouteImport } from './routes/dashboard/membro/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardMembroTrilhasRouteImport } from './routes/dashboard/membro/trilhas'
import { Route as DashboardMembroRankingRouteImport } from './routes/dashboard/membro/ranking'
import { Route as DashboardMembroProgressoRouteImport } from './routes/dashboard/membro/progresso'
import { Route as DashboardMembroMateriaisRouteImport } from './routes/dashboard/membro/materiais'
import { Route as DashboardMembroLivesRouteImport } from './routes/dashboard/membro/lives'
import { Route as DashboardAdminUploadRouteImport } from './routes/dashboard/admin/upload'
import { Route as DashboardAdminTrilhasRouteImport } from './routes/dashboard/admin/trilhas'
import { Route as DashboardAdminSolicitacoesRouteImport } from './routes/dashboard/admin/solicitacoes'
import { Route as DashboardAdminRelatoriosRouteImport } from './routes/dashboard/admin/relatorios'
import { Route as DashboardAdminMembrosRouteImport } from './routes/dashboard/admin/membros'
import { Route as DashboardAdminLivesRouteImport } from './routes/dashboard/admin/lives'
import { Route as DashboardAdminClientesRouteImport } from './routes/dashboard/admin/clientes'
import { Route as DashboardAdminAcessoRouteImport } from './routes/dashboard/admin/acesso'
import { Route as DashboardMembroTrilhaIdRouteImport } from './routes/dashboard/membro/trilha.$id'
import { Route as DashboardMembroPlayerIdRouteImport } from './routes/dashboard/membro/player.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMembroRoute = DashboardMembroRouteImport.update({
  id: '/dashboard/membro',
  path: '/dashboard/membro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMembroIndexRoute = DashboardMembroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardMembroTrilhasRoute = DashboardMembroTrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardMembroRankingRoute = DashboardMembroRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardMembroProgressoRoute =
  DashboardMembroProgressoRouteImport.update({
    id: '/progresso',
    path: '/progresso',
    getParentRoute: () => DashboardMembroRoute,
  } as any)
const DashboardMembroMateriaisRoute =
  DashboardMembroMateriaisRouteImport.update({
    id: '/materiais',
    path: '/materiais',
    getParentRoute: () => DashboardMembroRoute,
  } as any)
const DashboardMembroLivesRoute = DashboardMembroLivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardAdminUploadRoute = DashboardAdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTrilhasRoute = DashboardAdminTrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSolicitacoesRoute =
  DashboardAdminSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminRelatoriosRoute =
  DashboardAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminMembrosRoute = DashboardAdminMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminLivesRoute = DashboardAdminLivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminClientesRoute = DashboardAdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAcessoRoute = DashboardAdminAcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardMembroTrilhaIdRoute = DashboardMembroTrilhaIdRouteImport.update({
  id: '/trilha/$id',
  path: '/trilha/$id',
  getParentRoute: () => DashboardMembroRoute,
} as any)
const DashboardMembroPlayerIdRoute = DashboardMembroPlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => DashboardMembroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/membro': typeof DashboardMembroRouteWithChildren
  '/dashboard/admin/acesso': typeof DashboardAdminAcessoRoute
  '/dashboard/admin/clientes': typeof DashboardAdminClientesRoute
  '/dashboard/admin/lives': typeof DashboardAdminLivesRoute
  '/dashboard/admin/membros': typeof DashboardAdminMembrosRoute
  '/dashboard/admin/relatorios': typeof DashboardAdminRelatoriosRoute
  '/dashboard/admin/solicitacoes': typeof DashboardAdminSolicitacoesRoute
  '/dashboard/admin/trilhas': typeof DashboardAdminTrilhasRoute
  '/dashboard/admin/upload': typeof DashboardAdminUploadRoute
  '/dashboard/membro/lives': typeof DashboardMembroLivesRoute
  '/dashboard/membro/materiais': typeof DashboardMembroMateriaisRoute
  '/dashboard/membro/progresso': typeof DashboardMembroProgressoRoute
  '/dashboard/membro/ranking': typeof DashboardMembroRankingRoute
  '/dashboard/membro/trilhas': typeof DashboardMembroTrilhasRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/membro/': typeof DashboardMembroIndexRoute
  '/dashboard/membro/player/$id': typeof DashboardMembroPlayerIdRoute
  '/dashboard/membro/trilha/$id': typeof DashboardMembroTrilhaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin/acesso': typeof DashboardAdminAcessoRoute
  '/dashboard/admin/clientes': typeof DashboardAdminClientesRoute
  '/dashboard/admin/lives': typeof DashboardAdminLivesRoute
  '/dashboard/admin/membros': typeof DashboardAdminMembrosRoute
  '/dashboard/admin/relatorios': typeof DashboardAdminRelatoriosRoute
  '/dashboard/admin/solicitacoes': typeof DashboardAdminSolicitacoesRoute
  '/dashboard/admin/trilhas': typeof DashboardAdminTrilhasRoute
  '/dashboard/admin/upload': typeof DashboardAdminUploadRoute
  '/dashboard/membro/lives': typeof DashboardMembroLivesRoute
  '/dashboard/membro/materiais': typeof DashboardMembroMateriaisRoute
  '/dashboard/membro/progresso': typeof DashboardMembroProgressoRoute
  '/dashboard/membro/ranking': typeof DashboardMembroRankingRoute
  '/dashboard/membro/trilhas': typeof DashboardMembroTrilhasRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/membro': typeof DashboardMembroIndexRoute
  '/dashboard/membro/player/$id': typeof DashboardMembroPlayerIdRoute
  '/dashboard/membro/trilha/$id': typeof DashboardMembroTrilhaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/membro': typeof DashboardMembroRouteWithChildren
  '/dashboard/admin/acesso': typeof DashboardAdminAcessoRoute
  '/dashboard/admin/clientes': typeof DashboardAdminClientesRoute
  '/dashboard/admin/lives': typeof DashboardAdminLivesRoute
  '/dashboard/admin/membros': typeof DashboardAdminMembrosRoute
  '/dashboard/admin/relatorios': typeof DashboardAdminRelatoriosRoute
  '/dashboard/admin/solicitacoes': typeof DashboardAdminSolicitacoesRoute
  '/dashboard/admin/trilhas': typeof DashboardAdminTrilhasRoute
  '/dashboard/admin/upload': typeof DashboardAdminUploadRoute
  '/dashboard/membro/lives': typeof DashboardMembroLivesRoute
  '/dashboard/membro/materiais': typeof DashboardMembroMateriaisRoute
  '/dashboard/membro/progresso': typeof DashboardMembroProgressoRoute
  '/dashboard/membro/ranking': typeof DashboardMembroRankingRoute
  '/dashboard/membro/trilhas': typeof DashboardMembroTrilhasRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/membro/': typeof DashboardMembroIndexRoute
  '/dashboard/membro/player/$id': typeof DashboardMembroPlayerIdRoute
  '/dashboard/membro/trilha/$id': typeof DashboardMembroTrilhaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard/admin'
    | '/dashboard/membro'
    | '/dashboard/admin/acesso'
    | '/dashboard/admin/clientes'
    | '/dashboard/admin/lives'
    | '/dashboard/admin/membros'
    | '/dashboard/admin/relatorios'
    | '/dashboard/admin/solicitacoes'
    | '/dashboard/admin/trilhas'
    | '/dashboard/admin/upload'
    | '/dashboard/membro/lives'
    | '/dashboard/membro/materiais'
    | '/dashboard/membro/progresso'
    | '/dashboard/membro/ranking'
    | '/dashboard/membro/trilhas'
    | '/dashboard/admin/'
    | '/dashboard/membro/'
    | '/dashboard/membro/player/$id'
    | '/dashboard/membro/trilha/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/admin/acesso'
    | '/dashboard/admin/clientes'
    | '/dashboard/admin/lives'
    | '/dashboard/admin/membros'
    | '/dashboard/admin/relatorios'
    | '/dashboard/admin/solicitacoes'
    | '/dashboard/admin/trilhas'
    | '/dashboard/admin/upload'
    | '/dashboard/membro/lives'
    | '/dashboard/membro/materiais'
    | '/dashboard/membro/progresso'
    | '/dashboard/membro/ranking'
    | '/dashboard/membro/trilhas'
    | '/dashboard/admin'
    | '/dashboard/membro'
    | '/dashboard/membro/player/$id'
    | '/dashboard/membro/trilha/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard/admin'
    | '/dashboard/membro'
    | '/dashboard/admin/acesso'
    | '/dashboard/admin/clientes'
    | '/dashboard/admin/lives'
    | '/dashboard/admin/membros'
    | '/dashboard/admin/relatorios'
    | '/dashboard/admin/solicitacoes'
    | '/dashboard/admin/trilhas'
    | '/dashboard/admin/upload'
    | '/dashboard/membro/lives'
    | '/dashboard/membro/materiais'
    | '/dashboard/membro/progresso'
    | '/dashboard/membro/ranking'
    | '/dashboard/membro/trilhas'
    | '/dashboard/admin/'
    | '/dashboard/membro/'
    | '/dashboard/membro/player/$id'
    | '/dashboard/membro/trilha/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardMembroRoute: typeof DashboardMembroRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/membro': {
      id: '/dashboard/membro'
      path: '/dashboard/membro'
      fullPath: '/dashboard/membro'
      preLoaderRoute: typeof DashboardMembroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/membro/': {
      id: '/dashboard/membro/'
      path: '/'
      fullPath: '/dashboard/membro/'
      preLoaderRoute: typeof DashboardMembroIndexRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/membro/trilhas': {
      id: '/dashboard/membro/trilhas'
      path: '/trilhas'
      fullPath: '/dashboard/membro/trilhas'
      preLoaderRoute: typeof DashboardMembroTrilhasRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/ranking': {
      id: '/dashboard/membro/ranking'
      path: '/ranking'
      fullPath: '/dashboard/membro/ranking'
      preLoaderRoute: typeof DashboardMembroRankingRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/progresso': {
      id: '/dashboard/membro/progresso'
      path: '/progresso'
      fullPath: '/dashboard/membro/progresso'
      preLoaderRoute: typeof DashboardMembroProgressoRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/materiais': {
      id: '/dashboard/membro/materiais'
      path: '/materiais'
      fullPath: '/dashboard/membro/materiais'
      preLoaderRoute: typeof DashboardMembroMateriaisRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/lives': {
      id: '/dashboard/membro/lives'
      path: '/lives'
      fullPath: '/dashboard/membro/lives'
      preLoaderRoute: typeof DashboardMembroLivesRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/admin/upload': {
      id: '/dashboard/admin/upload'
      path: '/upload'
      fullPath: '/dashboard/admin/upload'
      preLoaderRoute: typeof DashboardAdminUploadRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/trilhas': {
      id: '/dashboard/admin/trilhas'
      path: '/trilhas'
      fullPath: '/dashboard/admin/trilhas'
      preLoaderRoute: typeof DashboardAdminTrilhasRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/solicitacoes': {
      id: '/dashboard/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/dashboard/admin/solicitacoes'
      preLoaderRoute: typeof DashboardAdminSolicitacoesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/relatorios': {
      id: '/dashboard/admin/relatorios'
      path: '/relatorios'
      fullPath: '/dashboard/admin/relatorios'
      preLoaderRoute: typeof DashboardAdminRelatoriosRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/membros': {
      id: '/dashboard/admin/membros'
      path: '/membros'
      fullPath: '/dashboard/admin/membros'
      preLoaderRoute: typeof DashboardAdminMembrosRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/lives': {
      id: '/dashboard/admin/lives'
      path: '/lives'
      fullPath: '/dashboard/admin/lives'
      preLoaderRoute: typeof DashboardAdminLivesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/clientes': {
      id: '/dashboard/admin/clientes'
      path: '/clientes'
      fullPath: '/dashboard/admin/clientes'
      preLoaderRoute: typeof DashboardAdminClientesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/acesso': {
      id: '/dashboard/admin/acesso'
      path: '/acesso'
      fullPath: '/dashboard/admin/acesso'
      preLoaderRoute: typeof DashboardAdminAcessoRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/membro/trilha/$id': {
      id: '/dashboard/membro/trilha/$id'
      path: '/trilha/$id'
      fullPath: '/dashboard/membro/trilha/$id'
      preLoaderRoute: typeof DashboardMembroTrilhaIdRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
    '/dashboard/membro/player/$id': {
      id: '/dashboard/membro/player/$id'
      path: '/player/$id'
      fullPath: '/dashboard/membro/player/$id'
      preLoaderRoute: typeof DashboardMembroPlayerIdRouteImport
      parentRoute: typeof DashboardMembroRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAcessoRoute: typeof DashboardAdminAcessoRoute
  DashboardAdminClientesRoute: typeof DashboardAdminClientesRoute
  DashboardAdminLivesRoute: typeof DashboardAdminLivesRoute
  DashboardAdminMembrosRoute: typeof DashboardAdminMembrosRoute
  DashboardAdminRelatoriosRoute: typeof DashboardAdminRelatoriosRoute
  DashboardAdminSolicitacoesRoute: typeof DashboardAdminSolicitacoesRoute
  DashboardAdminTrilhasRoute: typeof DashboardAdminTrilhasRoute
  DashboardAdminUploadRoute: typeof DashboardAdminUploadRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAcessoRoute: DashboardAdminAcessoRoute,
  DashboardAdminClientesRoute: DashboardAdminClientesRoute,
  DashboardAdminLivesRoute: DashboardAdminLivesRoute,
  DashboardAdminMembrosRoute: DashboardAdminMembrosRoute,
  DashboardAdminRelatoriosRoute: DashboardAdminRelatoriosRoute,
  DashboardAdminSolicitacoesRoute: DashboardAdminSolicitacoesRoute,
  DashboardAdminTrilhasRoute: DashboardAdminTrilhasRoute,
  DashboardAdminUploadRoute: DashboardAdminUploadRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardMembroRouteChildren {
  DashboardMembroLivesRoute: typeof DashboardMembroLivesRoute
  DashboardMembroMateriaisRoute: typeof DashboardMembroMateriaisRoute
  DashboardMembroProgressoRoute: typeof DashboardMembroProgressoRoute
  DashboardMembroRankingRoute: typeof DashboardMembroRankingRoute
  DashboardMembroTrilhasRoute: typeof DashboardMembroTrilhasRoute
  DashboardMembroIndexRoute: typeof DashboardMembroIndexRoute
  DashboardMembroPlayerIdRoute: typeof DashboardMembroPlayerIdRoute
  DashboardMembroTrilhaIdRoute: typeof DashboardMembroTrilhaIdRoute
}

const DashboardMembroRouteChildren: DashboardMembroRouteChildren = {
  DashboardMembroLivesRoute: DashboardMembroLivesRoute,
  DashboardMembroMateriaisRoute: DashboardMembroMateriaisRoute,
  DashboardMembroProgressoRoute: DashboardMembroProgressoRoute,
  DashboardMembroRankingRoute: DashboardMembroRankingRoute,
  DashboardMembroTrilhasRoute: DashboardMembroTrilhasRoute,
  DashboardMembroIndexRoute: DashboardMembroIndexRoute,
  DashboardMembroPlayerIdRoute: DashboardMembroPlayerIdRoute,
  DashboardMembroTrilhaIdRoute: DashboardMembroTrilhaIdRoute,
}

const DashboardMembroRouteWithChildren = DashboardMembroRoute._addFileChildren(
  DashboardMembroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardMembroRoute: DashboardMembroRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
